server:
  port: 8086

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.75.157:3306/service-driver-user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.75.157:8848

  application:
    name: service-driver-user

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
